from __future__ import annotations

from enum import StrEnum


class ErrorCode(StrEnum):
    INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR"
    INVALID_REQUEST_BODY = "INVALID_REQUEST_BODY"
    INVALID_FILE_EXTENSION = "INVALID_FILE_EXTENSION"
    INVALID_PROJECT_FLOOR_INPUT = "INVALID_PROJECT_FLOOR_INPUT"
    INVALID_UUID_FORMAT = "INVALID_UUID_FORMAT"
    FILE_SAVE_FAILED = "FILE_SAVE_FAILED"
    UPLOADED_FILE_NOT_FOUND = "UPLOADED_FILE_NOT_FOUND"
    INVALID_PROJECT_ID = "INVALID_PROJECT_ID"
    INVALID_FLOOR_ID = "INVALID_FLOOR_ID"
    INVALID_PROJECT_FLOOR_PAIR = "INVALID_PROJECT_FLOOR_PAIR"
    ANALYSIS_FAILED = "ANALYSIS_FAILED"
    WALL_EXTRACTION_FAILED = "WALL_EXTRACTION_FAILED"
    EXTERNAL_SERVICE_REQUEST_FAILED = "EXTERNAL_SERVICE_REQUEST_FAILED"
    INVALID_EXTERNAL_RESPONSE = "INVALID_EXTERNAL_RESPONSE"
    RF_SIMULATION_FAILED = "RF_SIMULATION_FAILED"
    DB_CONNECTION_FAILED = "DB_CONNECTION_FAILED"
    SCENE_DRAFT_SAVE_FAILED = "SCENE_DRAFT_SAVE_FAILED"
    MEASUREMENT_LINK_NOT_FOUND = "MEASUREMENT_LINK_NOT_FOUND"
    MEASUREMENT_LINK_EXPIRED = "MEASUREMENT_LINK_EXPIRED"
    MEASUREMENT_SESSION_NOT_FOUND = "MEASUREMENT_SESSION_NOT_FOUND"
    MEASUREMENT_SESSION_ALREADY_COMPLETED = "MEASUREMENT_SESSION_ALREADY_COMPLETED"
    INVALID_CREDENTIALS = "INVALID_CREDENTIALS"
    EMAIL_ALREADY_EXISTS = "EMAIL_ALREADY_EXISTS"
    UNAUTHORIZED = "UNAUTHORIZED"
    INVALID_TOKEN = "INVALID_TOKEN"
    TOKEN_EXPIRED = "TOKEN_EXPIRED"
    USER_NOT_FOUND = "USER_NOT_FOUND"
    PROJECT_NOT_FOUND = "PROJECT_NOT_FOUND"
    FLOOR_NOT_FOUND = "FLOOR_NOT_FOUND"
    SCENE_DRAFT_NOT_FOUND = "SCENE_DRAFT_NOT_FOUND"
    FORBIDDEN = "FORBIDDEN"

    ASSET_NOT_FOUND = "ASSET_NOT_FOUND"
    INVALID_ASSET_TYPE = "INVALID_ASSET_TYPE"
    FILE_STORAGE_ERROR = "FILE_STORAGE_ERROR"

    DRAFT_ROOM_NOT_FOUND = "DRAFT_ROOM_NOT_FOUND"
    DRAFT_WALL_NOT_FOUND = "DRAFT_WALL_NOT_FOUND"
    DRAFT_OPENING_NOT_FOUND = "DRAFT_OPENING_NOT_FOUND"
    DRAFT_OBJECT_NOT_FOUND = "DRAFT_OBJECT_NOT_FOUND"
    INVALID_GEOMETRY = "INVALID_GEOMETRY"

    SCENE_VERSION_NOT_FOUND = "SCENE_VERSION_NOT_FOUND"
    DRAFT_ALREADY_PROMOTED = "DRAFT_ALREADY_PROMOTED"
    SCENE_VERSION_CONFLICT = "SCENE_VERSION_CONFLICT"

    ROOM_NOT_FOUND = "ROOM_NOT_FOUND"
    WALL_NOT_FOUND = "WALL_NOT_FOUND"
    OPENING_NOT_FOUND = "OPENING_NOT_FOUND"
    OBJECT_NOT_FOUND = "OBJECT_NOT_FOUND"

    MATERIAL_NOT_FOUND = "MATERIAL_NOT_FOUND"
    MATERIAL_RF_PROFILE_NOT_FOUND = "MATERIAL_RF_PROFILE_NOT_FOUND"
    MATERIAL_HYPOTHESIS_NOT_FOUND = "MATERIAL_HYPOTHESIS_NOT_FOUND"


class AppError(Exception):
    def __init__(self, code: ErrorCode, message: str, status_code: int):
        self.code = code
        self.message = message
        self.status_code = status_code
        super().__init__(message)
